### ISSUE TITLE
support scrolloff

### ISSUE THREAD

**Issue by RAV64** [jake-stewart/multicursor.nvim#27]
Using this keymap 
``` lua
set({ "n", "v" }, "<c-n>", function()
  mc.addCursor("*")
  vim.cmd("nohlsearch")
end)
```
if the location of the next subject exists in area where vim.opt.scrolloff would have an effect the jump ends up in the wrong place.

https://github.com/user-attachments/assets/64a5d873-b1f8-459d-81b0-7a60dcbe6a08

In this example I'm calling this keybind 4 times. The 16 lines that are below my cursor after the first 2 calls match my opt.scrolloff of 16. If scrolloff is set to 0 this works fine.

**Comment by jake-stewart** [comment]
It should be fixed now, try `:Lazy update` and let me know. Thanks

**Comment by RAV64** [comment]
Still happens when jumping from end of the file back to top

**Comment by jake-stewart** [comment]
@RAV64 I have made some improvements to scrolloff. Try `:Lazy update`.

There is an issue when at the end of a file where the view may jump. It should not cause any problems with your cursors. I'm not sure if this is fixable because `vim.fn.line("w$")` returns an outdated value, but I will investigate further another time.

Let me know if there are any more major problems.

**Comment by jake-stewart** [comment]
@RAV64 Try now.

**Comment by RAV64** [comment]
Initial testing has been great, awesome work 👍🏻 Thanks for the quick action. I'll let you know if I run into further issues.
