### ISSUE TITLE
<ESC> not work in lazyvim

### ISSUE THREAD

**Issue by alanxmay** [jake-stewart/multicursor.nvim#33]
<ESC> not work in lazyvim, can't clean multi cursor.

**Comment by alanxmay** [comment]
following [lazyvim doc - adding--disabling-plugin-keymaps](http://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps) solved.

**Comment by mohnasir-gh** [comment]
Can you please share your config. I am facing the same issue @alanxmay

**Comment by alanxmay** [comment]
@mohnasir-gh Sorry for the late reply. I just follow the instruction by [lazyvim doc](http://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps) then add `keys` field.

```lua
return {
  "jake-stewart/multicursor.nvim",
  event = "VeryLazy",
  branch = "1.0",
  keys = {
    {
      "<esc>",
      function()
        local mc = require("multicursor-nvim")
        if not mc.cursorsEnabled() then
          mc.enableCursors()
        elseif mc.hasCursors() then
          mc.clearCursors()
        else
          -- Default <esc> handler.
        end
      end,
    },
  },
  config = function()
    local mc = require("multicursor-nvim")

    mc.setup()
    ....
}
```

**Comment by Sairyss** [comment]
Problem with the solution above (at least for me) is that it breaks `<esc>` default behavior in other places of LazyVim, for example clearing of highlighted text after searching with `/` and also clearing the search of flash.nvim after pressing `f` and such.
Clearing highlighted text I fixed by adding `vim.cmd("noh")` in the last `else` condition, but I couldn't solve issue with clearing flash.nvim searches yet. Potentially there may be more clashes in `<esc>` key behavior in LazyVim so I remapped it from <esc> to <m-esc> for now.

**Comment by jake-stewart** [comment]
@Sairyss 

this should do the trick for you:

```lua
pcall(function()
    require("flash.state"):hide()
end)
vim.cmd.noh()
```

wrapped in a `pcall` so it works without flash being installed.

**Comment by Sairyss** [comment]
@jake-stewart this seems to work only when pressing `f` or `t` and immediately `<esc>`, but if searching something after pressing `f`/`t`  than `<esc>` does nothing. For example: running `f.` highlights all `.` but `<esc>` now doesn't hide the search. Also when repeating find with `;` and `,`  pressing `<esc>` does nothing, but it should hide the flash ui.

**Comment by jake-stewart** [comment]
@Sairyss I updated the block of code a moment ago. I have tested and this version works for me.

**Comment by Sairyss** [comment]
@jake-stewart thanks, this one works better. Though there is a bug still, when repeating search, canceling, and then starting a new one - it continues with the old one instead of starting a new search. For example executing `f.ff` jumps to the third `.`, then `<esc>` hides the ui, then if you start a new search with `f` it continues searching for `.` instead of starting a new one like it should.

**Comment by jake-stewart** [comment]
man, flash.nvim is a nightmare. to be fair, i dont think it is meant to be a public api.

@Sairyss this seems to work well:

```lua
require("flash.repeat").get_state("jump"):hide()
local c = require("flash.plugins.char")
c.jumping = false;
c.char = nil;
vim.cmd.noh()
```
